"""Increase password field length

Revision ID: 441580ecb77f
Revises: 82e133fe5300
Create Date: 2024-08-14 10:50:36.568710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '441580ecb77f'
down_revision = '82e133fe5300'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
